crystal-lang-tools/scry

- Dockerfile
- spec/scry/context_spec.cr
- spec/scry/initialize_spec.cr
- spec/scry/request_spec.cr
- spec/scry/response_spec.cr
- spec/scry/update_config_spec.cr
- spec/spec_helper.cr
- src/scry/analyzer.cr
- src/scry/context.cr
- src/scry/environment_config.cr
- src/scry/initialize.cr
- src/scry/log.cr
- src/scry/protocol/diagnostic.cr
- src/scry/protocol/initialize_params.cr
- src/scry/protocol/message.cr
- src/scry/protocol/notification.cr
- src/scry/protocol/publish_diagnostics_notification.cr
- src/scry/protocol/response_message.cr
- src/scry/protocol/server_capabilities.cr
Hi @kofno I;m working in a [crystal extension](https://github.com/faustinoaq/vscode-crystal-lang) and seems that Node.js implementation is a bit heavy.
Scry works very well, however is heavy in some big projects like this, but isn't Scry side issue but crystal side sometimes is slow, see [Reddit Issue](https://www.reddit.com/r/crystal_programming/comments/6hyzuv/crystal_compiler_time/).
BTW, this PR passes all the specs:
```
$ crystal spec --no-debug -s
Parse:                             00:00:00.0001888 (   0.19MB)
Semantic (top level):              00:00:00.8713985 (  82.64MB)
Semantic (new):                    00:00:00.0053171 (  90.64MB)
Semantic (type declarations):      00:00:00.0788579 (  98.64MB)
Semantic (abstract def check):     00:00:00.0030189 (  98.64MB)
Semantic (ivars …
```
> Update latest crystal

- Makefile
- README.md
- spec/spec_helper.cr
- src/scry/formatter.cr
Hi @kofno !
I found some issues while using Scry:
- Formatter don't replace all when old document is bigger that new one (Fixed with this PR)
- Sometimes Diagnostics are keep even when code is correct (Strange bug, I didn't know how to fix it)
Also I added `-s` flag to show stats when using make.
> Fix formatting bug and show stats when use make

- src/scry/analyzer.cr
- src/scry/implementations.cr
Hi @kofno I did some improves.
- ~~Verify that document text is different before analyze.~~
- Ensure to execute Garbage Collector. (free some MB)
- Avoid to check files shards and crystal lib.
> Improves performance when analyzing on save.

- src/scry/protocol/did_change_configuration_params.cr
- src/scry/protocol/settings.cr
This PR do:
- Allow to add new clients.
- Use type struct for each client supported.
Related to PR https://github.com/kofno/scry/pull/15#issuecomment-317438702
This is the first PR to change Scry to be more client agnostic.
Also I want to add [mainFile](https://github.com/faustinoaq/vscode-crystal-lang#33-mainfile) in the future. It's useful for [Amber](http://www.ambercr.io/) projects by example.
> Add new client configuration.

- src/scry/log.cr
Hi @kofno :smile: 
This PR does:
- Use Tempfile to allow crossplatform support for `scry.out`
- Avoid to write `scry.out` on `/` when `Dir.current` is not set (Fix #17).
See: https://devdocs.io/crystal/api/0.23.0/tempfile
> Fix #17 using Tempfile

- .travis.yml
- spec/scry/implementations_spec.cr
This does abandon the Docker solution you were using before. However using the virtualized environment Travis CI provides is more inline with the default implementation being worked on for Crystal projects on Travis. Sadly, at the moment the default Crystal config for Travis does not work with this project. This is being worked on though (ref: travis-ci/travis-build#1117).
This setup installs Crystal on Ubuntu and macOS, runs the specs, and when successful builds a tar of the compiled scry binary. If running on a tagged commit Travis publishes that tarred binary to the tagged release on the GitHub Releases page. This encourages version tagging and maintaining a living Changelog on the GitHub Releases page.
I did have to disable a spec as it was dependent on a Travis environment constant …
> Configure Travis to publish Linux and macOS builds

- spec/spec_helper.cr
- src/scry/context.cr
- src/scry/formatter.cr
- src/scry/protocol/initialize_params.cr
- src/scry/protocol/notification_message.cr
- src/scry/protocol/request_message.cr
It seems a couple of the Params are in the wrong MessageType.
Based on the LSP 3.0 Spec the [`TextDocumentPositionParams`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textdocumentpositionparams)  and [`DocumentFormattingParams`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-formatting-request) are associated with Request Messages
> Move params to RequestMessage

- src/scry/protocol/notification_message.cr
According to LSP 3.0 spec regarding [NotificationMessages](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#notification-message) the id field is not part of the spec.  This PR removes the optional id from the NotificationMessage type
> Remove id from NotificationMessage

- spec/scry/message_spec.cr
- spec/spec_helper.cr
- src/scry/context.cr
- src/scry/protocol/notification_message.cr
- src/scry/protocol/request_message.cr
- src/scry/protocol/text_document_params.cr
- src/scry/protocol/text_document_position_params.cr
Fixes a couple message types
- Moves didSave/didClose notifications to Notification messages type
- Makes didSave v3 compliant
- Creates generic `TextDocumentParams` params struct that contains a `TextDocumentIdentifer` or `VersionedTextDocumentIdentifier` and optional fields
- Makes `TextDocumentPositionParams` explicit
> Move didSave/didClose messages to Notifications

- spec/scry/message_spec.cr
- spec/scry/protocol/void_params_spec.cr
- spec/spec_helper.cr
- src/scry/context.cr
- src/scry/protocol/notification_message.cr
- src/scry/protocol/void_params.cr
Allows Scry to receive the [initialized notification](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialized). 
Adds new param type `VoidParams` which is an empty JSON object used by the initialized notification
> Adds initialized notification

- spec/spec_helper.cr
- src/scry/formatter.cr
Fixes https://github.com/crystal-lang-tools/scry/issues/35
- Formats document with a single TextEdit rather than many since we end up formatting the entire source anyway
> Send back single formatted TextEdit

- spec/scry/response_spec.cr
- spec/scry/symbol_spec.cr
- src/scry/context.cr
- src/scry/protocol/request_message.cr
- src/scry/protocol/response_message.cr
- src/scry/protocol/server_capabilities.cr
- src/scry/protocol/symbol_information.cr
- src/scry/symbol.cr
- src/scry/text_document.cr
Based on https://github.com/crystal-lang-tools/scry/issues/38
This implements initial Symbol support for Scry.  I originally started to use `CrystalCtags` but feel that was kind of written to do something similar but not exactly the same.  Some changes would needed to be made to Ctags in order for it to work for Scry's purposes I believe, and it might just be easier to have our own implementation.
This PR adds a Scry specific `SymbolVisitor` which  traverses the AST and builds a list of Symbols to be sent as the response.  I have only added support for Class/Module/Enum/Struct/Methods in this initial PR.  Let me know what you think and if you think this is a good way to proceed!
> Symbol Initial Implementation

- src/scry/protocol/diagnostic.cr
Fix typo in DiagnosticSeverity enum
> Fix typo in enum

- .gitignore
- .travis.yml
- Dockerfile
- Makefile
- bin/ci
* Got the bin/ci file from the crystal lang repo and removed what wasn't needed.
* Updated the Dockerfile to a more current version of crystal.
* Started using the Dockerfile to build the image in travis.
* Removed the Makefile cause it doesn't seem it is necessary.
> Try to fix travis

- spec/scry/symbol_spec.cr
- src/scry/symbol.cr
Adds property and variable symbols to Scry, in line with how `vscode-crystal-lang` defines them.
Related to #38
> Add property and variable symbols

- .travis.yml
- Dockerfile
- README.md
- bin/ci
- spec/scry/initialize_spec.cr
- src/scry/analyzer.cr
- src/scry/implementations.cr
- src/scry/missing_methods.cr
- src/scry/parse_analyzer.cr
- src/scry/publish_diagnostic.cr
Hi, this PR implements lightweight features:
- Lightweight analyzer and implementations
- Avoid heavy compiler dependencies
- Use external process to free up memory
Before:
With this PR changes:
Same features and behaviors, more RAM friendly and lightweight binary `19.2MB` vs `4.7MB`
Oh, also compilation time has been reduced drastically:
```
$ time crystal build src/scry.cr -s -p --no-debug
Parse:                             00:00:00.000316202 (   0.25MB)
Semantic (top level):              00:00:00.404959721 (  52.33MB)
Semantic (new):                    00:00:00.002962556 (  52.33MB)
Semantic (type declarations):      00:00:00.032710793 (  52.33MB)
Semantic (abstract def check):     00:00:00.002463025 (  52.33MB)
Semantic (ivars initializers):     00:00:00.001851865 (  52.33MB)
Semantic …
```
> Make scry faster and lightweight

- src/scry/context.cr
- src/scry/formatter.cr
- src/scry/text_document.cr
Currently scry can't format an unsaved document, with this PR now you can format even a untitled file :tada: 
/cc @crystal-lang-tools/scry
> Allow formatting unsaved document

- spec/fixtures/completion/tree.cr
- spec/scry/completion_resolver_spec.cr
- src/scry/completion/method_call_context.cr
- src/scry/completion/method_db.cr
- src/scry/completion_resolver.cr
- src/scry/protocol/completion_item.cr
Adds the method signature to the completion box and the documentation of the method if it has any.
> Adds documentation resolve to method completion

- src/scry.cr
- src/scry/context.cr
- src/scry/request.cr
Fixes https://github.com/crystal-lang-tools/scry/issues/69 and replaces #70 
/cc @damieng
> Handle exit and shutdown request

- src/scry/initializer.cr
- src/scry/protocol/initialize_params.cr
- src/scry/workspace.cr
Fixes #72 
PR summary:
* Save compatibility with scry code base
* Adds rootUri as alternative non nilable
* Keep rootPath as default and use rootUri when this isn't available
* Makes process_id nilable
> Fixes InitializeParams to follow LSP specification

- src/scry/analyzer.cr
- src/scry/publish_diagnostic.cr
- src/scry/text_document.cr
This PR basically adds the following feature: Analyze the code twice if undefined symbol is found on diagnostics result
The rules:
1. first time analyzes a single file and stop if no error
2. second time analyzes the entire project requiring the first level files inside src folder
**Summary of changes:**
* Add method inside_crystal_path? to avoid analizing lib and stdlib
* Send clean diagnostics for all files when a full project is analyzed
* Allow analyze files with implicit requires (main file style)
* Adds --no-debug flag for speed up compilation
* Add fake file .scry.cr to analyze a full project (aka main file)
* Remove the fake file .scry.cr from diagnostic list
* Add untitled: to the uri_to_filename method
**Use case:** very useful on those projects where you have a main file that …
> Analyze files with implicit requires

- spec/scry/implementations_spec.cr
- spec/scry/response_spec.cr
- src/scry/context.cr
- src/scry/implementations.cr
- src/scry/protocol/diagnostic.cr
**NOTE:** This feature doesn't affect scry performance, just increase the scope available to search methods and dependencies without requiring files explicitly (common practice in crystal projects)
Fixes #29
* Use root_uri from workspace
* Add get_scope to set scope to src folder on standard crystal projects
* Also get_scope sets the scope to the worspace if no src folder exists
* Send empty implementation message if an error is found...
* ...enabling the message "not found implementation" in the LSP client
The rules are:
1. If your project has a `src` directory (common on crystal projects) then you should have a main file that requires all others using `require "./**/*"` or similar
2. If your project doesn't have a `src` folder then all the workspace is analyzed in aims to search symbols …
> Search implementations in files with implicit requires

- bin/ci
- bin/format
- spec/fixtures/completion/method_db/invalid_sample.cr
- spec/fixtures/completion/method_db/sample_2.cr
- spec/scry/completion/method_db_spec.cr
- src/scry/completion/method_db.cr
Fix for #60 
I added an invalid sample to the the spec fixtures, it broke the format check :(
> 60 laginha87 methoddb generation more resilient

- spec/scry/completion/method_call_context_spec.cr
- src/scry/completion/method_call_context.cr
Fixes the following issue.
On this scenario:
```
a = A.new(1)
a.
```
The current implementation identifies the type of a as an integer when it should be A.
> Fixes autocompletion when constructor has integer or boolean params

- spec/scry/completion/dependency_graph_spec.cr
- spec/scry/workspace_spec.cr
- src/scry/completion/dependency_graph.cr
- src/scry/default_crystal_path.cr
- src/scry/workspace.cr
Hi scry community! :grinning: 
More fixes :tada: 
This check availability for a file inside `dependency_graph`  before call it. 
Useful for untitled files and external files
Fixes #91 
Fixes #59 
/cc @laginha87
> Check file inside dependency_graph before using it

- spec/scry/response_spec.cr
- spec/scry/symbol_spec.cr
- src/scry/context.cr
- src/scry/protocol/request_message.cr
- src/scry/protocol/server_capabilities.cr
- src/scry/protocol/workspace_symbol_params.cr
- src/scry/symbol.cr
> Add workspace symbols

- src/scry/symbol.cr
I just found this enhancement during development of rename feature
This will allow us to show code outline properly :tada:
> Add symbol end_position using end_location

- src/scry/completion/dependency_graph.cr
Currently when running the specs on my Mac I get a `Too many files open` error.  This is because when loading the DependencyGraph we are using the `File.each_line` iterator method, which does not close the file.  This changes the DependencyGraph to use the `File.each_line` method which yields to a block, and properly closes the File.
> Do not use File.each_line iterator to ensure Files are closed

- README.md
This PR change `crystal build` by `shards build` on README, so we can recommend to use our available target on `shard.yml`
```yml
targets:
scry:
main: src/scry.cr
```
> Use shards build

- src/scry/analyzer.cr
- src/scry/formatter.cr
- src/scry/hover_provider.cr
- src/scry/implementations.cr
Hi @crystal-lang-tools/scry team!
This PR add more information when an exception is triggered, so is easy to debug crystal bugs because exception itself doesn't give relevant info, just an JSON parse error, possible change here: https://github.com/crystal-lang/crystal/pull/5932 (But still not enough info)
> Log response on exception

- spec/scry/symbol_spec.cr
- src/scry/symbol.cr
Hi @crystal-lang-tools/scry team!
This PR removes `query_regex` because using regex can be ultra slow, also can produce unexpected behaviors :sweat_smile:
> Remove query_regex on workspace symbol search

- src/scry/protocol.cr
- src/scry/protocol/cancel_params.cr
- src/scry/protocol/did_open_text_document_params.cr
- src/scry/protocol/file_event.cr
- src/scry/protocol/formatting_options.cr
- src/scry/protocol/hover.cr
- src/scry/protocol/initialize_params.cr
- src/scry/protocol/log_message_params.cr
- src/scry/protocol/markup_content.cr
- src/scry/protocol/position.cr
- src/scry/protocol/response_error.cr
- src/scry/protocol/server_capabilities.cr
- src/scry/protocol/settings.cr
- src/scry/protocol/symbol_information.cr
- src/scry/protocol/text_document_identifier.cr
- src/scry/protocol/text_document_params.cr
- src/scry/protocol/trace.cr
- src/scry/protocol/versioned_text_document_identifier.cr
- src/scry/protocol/void_params.cr
- src/scry/protocol/workspace_symbol_params.cr
Small cleanup to remove all the `require "json"` littered throughout the Protocol namespace
> Require json once

- spec/spec_helper.cr
- src/scry/protocol/response_message.cr
Fixes #52 
Closes #140 
This might be a more simple solution to fixing #52.  According to the spec we should always emit the id field in a response, even if it is `null`
@bew would you be able to verify this?
> Always emit the id property for responses, even if null

- spec/scry/formatter_spec.cr
- spec/scry/workspace_spec.cr
- src/scry/context.cr
- src/scry/text_document.cr
- src/scry/workspace.cr
Attempting to clean up some the code.  It seems like we should decouple the Protocol params from the actual Workspace class.  In this case we were passing in the params, and then immediately instantiating a TextDocument, which we already had available prior to calling some of these Workspace methods.  Now we will just pass in a `TextDocument`.  
This also makes me wonder if we should either rename `TextDocument` to something like `SourceFile` or possibly rename the Workspace methods to something like `put_document` just to be consistent.
> Decouple Workspace from Protocol

- spec/protocol_helper.cr
- spec/scry/context_spec.cr
- spec/scry/message_spec.cr
- src/scry.cr
- src/scry/message.cr
Came across this repo when I was looking for something in Crystal to contribute to and I thought I'd dive in.  Starting from the beginning I noticed this `Message` class that was being initialized and `#parse` immediately called in all cases.  Seeing how the JSON was being handled was definitely interesting but I believe that the `Message` class would be more clear if there was just the one, class-level method.
Looking back at the history I see that this `Message.new(...).parse` is from the [very first commit](https://github.com/crystal-lang-tools/scry/commit/dffefb00e38fcb045252fcd3819cf8a7e1ba12a9?short_path=04c6e90#diff-62f71642256d6493b5a748976dc28bdaR28) when it was still called `Procedure`.
Hope to be able to contribute more soon!
> Make it clear that Message is a factory

- src/scry/analyzer.cr
Hi @crystal-lang-tools/scry team!
I have been working on several crystal projects latest weeks and I realize sometimes scry is very slow because is launching too much heavy crystal processes in background.
This change removes the implicit requires by removing `require "./src/*"` from analyzer, you still can use this behaivior by adding the explicit require inside your `.scry_main.cr` file.
BTW, I already have some progress in `.scry.yml` configuration, so you will be able to edit the main file very soon :wink:
> Only analyze twice if main file exists

- spec/scry/symbol_spec.cr
- src/scry/symbol.cr
Adds support for parsing of user-defined annotations (crystal-lang/crystal#6063).
I'm not overly familiar with this code base to apologies if I've butchered the implementation. Any suggestions / criticism / (constructive) abuse welcomed in the thread here prior merge.
Updated specs are passing and the build output is tested and running within [crystal-lang-tools/atom-ide-crystal](https://github.com/crystal-lang-tools/atom-ide-crystal).
> Add support for annotations

- README.md
It's quite possible that I missed something. But, if not, the default installation instructions do not build ```release``` versions and take, according to some crude benchmarking, 5x longer than necessary?
```
3364 files, time is   5.254480   0.124605   5.379085 (  5.311287)
```
```
Benchmarking: 3364 files, time is   0.916777   0.109408   1.026185 (  0.963096)
```
> Add --release flag to install instructions.

- Dockerfile
- spec/scry/client_spec.cr
- spec/scry/completion_provider_spec.cr
- src/scry.cr
- src/scry/analyzer.cr
- src/scry/completion/dependency_graph.cr
- src/scry/completion/method_db.cr
- src/scry/context.cr
- src/scry/formatter.cr
- src/scry/hover_provider.cr
- src/scry/implementations.cr
- src/scry/log.cr
- src/scry/request.cr
- src/scry/text_document.cr
- src/scry/update_config.cr
> Support Crystal 0.34.0

- src/scry/environment_config.cr
Due to change of quoting environment variables in crystal compiler crystal-lang/crystal/pull/9428 Scry interpreted them erroneously causing #173 and creating compiler's cache files in wrong location.
Fixes #173
> Fix compatibility for Crystal 0.35.0

- Dockerfile
- shard.lock
- shard.yml
- src/scry/hover_provider.cr
- src/scry/log.cr
- src/scry/parse_analyzer.cr
- src/scry/update_config.cr
I don't know the detail of the language specs and changing history of crystal. So I guess this PR does not actually support latest language specs.
But currently we can't even finish running tests in crystal 0.36.1. So this PR just fixes them.
Fixes https://github.com/crystal-lang-tools/scry/issues/179
Refs
---
* https://github.com/crystal-lang-tools/lsp/pull/6
* https://github.com/crystal-lang/crystal/pull/9527
* https://github.com/crystal-lang/crystal/pull/9293
* https://github.com/crystal-lang/crystal/pull/10197
> Follow crystal 0.36.1

- shard.lock
- shard.yml
Thanks for the quick merging https://github.com/crystal-lang-tools/lsp/pull/6 😄 
So we don't need workaround now.
> Update depending lsp repository

- .travis.yml
Current CI looks 🔴 https://travis-ci.org/github/crystal-lang-tools/scry/builds/761829382
I guess it came from Travis-CI supported old MacOS as the default...
https://github.com/Homebrew/discussions/discussions/461#discussioncomment-266166
https://docs.travis-ci.com/user/reference/osx/#macos-version
Current latest is below
> [WIP] Follow latest Homebrew

- shard.lock
The lock file wasn't updated when `shard.yml` was.
> lock the proper lsp version
